# Generated by Django 4.1.7 on 2023-06-22 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Race",
        ),
    ]
