# Generated by Django 4.1.7 on 2023-04-10 10:40

import character.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('race', models.PositiveSmallIntegerField(default=0)),
                ('char_class', models.PositiveSmallIntegerField(default=0)),
                ('stats', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=6)),
                ('spells', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=character.models.get_default_array, size=None)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=character.models.get_default_array, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=50)),
                ('param_value', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
    ]
