# Generated by Django 4.1.7 on 2023-03-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
