# Generated by Django 4.1.7 on 2023-03-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_character_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
