# Generated by Django 4.1.7 on 2023-03-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_character_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='class',
        ),
        migrations.AddField(
            model_name='character',
            name='char_class',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
