# Generated by Django 4.1.7 on 2023-04-09 15:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_remove_character_class_character_char_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=None, size=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=None, size=None),
        ),
    ]
