# Generated by Django 4.1.7 on 2023-04-09 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_character_items_alter_character_spells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=0, size=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=0, size=None),
        ),
    ]
